require("moonsc").import_tags()

-- Test that the else clause executes if <if> and <elseif> evaluate to false.
-- Baz should be the only event generated by the <if>.  bat is raised to catch
-- the case where the <else> clause fails and baz is not generated, i.e. it
-- makes sure that the test doesn't hang.

return _scxml{ initial="s0",
   _datamodel{
      _data{ id="var1", expr="0" },
   },

  _state{ id="s0",
      _onentry{
         _if{ cond="false",
            _raise{ event="foo" },
            _assign{ location="var1", expr="var1+1" },
         _elseif{ cond="false" },
            _raise{ event="bar" },
            _assign{ location="var1", expr="var1+1" },
         _else{},
            _raise{ event="baz" },
            _assign{ location="var1", expr="var1+1" },
         },
         _raise{ event="bat" },
      },
      _transition{ event="baz", cond="var1==1", target="pass" },
      _transition{ event="*", target="fail" },
   },
   
   _final{id='pass'},
   _final{id='fail'},
}

