
== Preface

This is the reference manual
of *MoonSC*, which is a http://www.lua.org[*Lua*] execution environment for 
https://en.wikipedia.org/wiki/State_diagram#Harel_statechart[*Harel statecharts*],
following the https://www.w3.org/TR/scxml/[*State&nbsp;Chart&nbsp;XML&nbsp;(SCXML)*] recommendation.
footnote:[This manual is written in
http://www.methods.co.nz/asciidoc/[AsciiDoc], rendered with
http://asciidoctor.org/[AsciiDoctor] and a CSS from the
https://github.com/asciidoctor/asciidoctor-stylesheet-factory[AsciiDoctor Stylesheet Factory].]

It is assumed that the reader is familiar with both SCXML
and the Lua programming language.

For convenience of reference, this document contains external (deep) links to the 
http://www.lua.org/manual/5.3/manual.html[Lua Reference Manual] and to the 
https://www.w3.org/TR/scxml/[SCXML Recommendation].

=== Getting and installing

For installation intructions, refer to the README file in the 
https://github.com/stetre/moonsc[*MoonSC official repository*]
on GitHub.

=== Module organization

The MoonSC module is loaded using Lua's 
http://www.lua.org/manual/5.3/manual.html#pdf-require[require]() and
returns a table containing the functions it provides 
(as usual with Lua modules). This manual assumes that such
table is named *moonsc*, i.e. that it is loaded with:

[source,lua,indent=1]
----
moonsc = require("moonsc")
----

but nothing forbids the use of a different name.

=== Examples

Complete examples can be found in the *examples/* directory of the release package.

=== License

MoonSC is released under the *MIT/X11 license* (same as
http://www.lua.org/license.html[Lua], and with the same only requirement to give proper
credits to the original author). 
The copyright notice is in the LICENSE file in the base directory
of the https://github.com/stetre/moonsc[official repository] on GitHub.

[[see-also]]
=== See also

MoonSC is part of https://github.com/stetre/moonlibs[MoonLibs], a collection of 
Lua libraries for graphics and audio programming.

